# Generated by Django 6.0.7 on 2026-07-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PROVIDER', 'Provider')], default='CLIENT', help_text='Whether the account books services (client) or offers them (provider).', max_length=10),
        ),
    ]
